frontend_news:
  resource: "@NewsBundle/Resources/config/routes/frontend/news.yaml"
  prefix:   /news

frontend_news_category:
  resource: "@NewsBundle/Resources/config/routes/frontend/news_category.yaml"
  prefix:   /news-category
